### ISSUE TITLE
linux qq登录怎么操作  需要图形界面吗

### ISSUE THREAD

**Issue by wzwei1990** [xys20071111/QQ-For-Linux-Docker#1]
qq登录怎么操作  需要图形界面吗

**Comment by xys20071111** [comment]
你看一下readme，操作完就能看到登陆界面。  
这个是日用时防止qq扫盘的，不是做bot的

**Comment by wzwei1990** [comment]
> 你看一下readme，操作完就能看到登陆界面。 这个是日用时防止qq扫盘的，不是做bot的

了解 想弄一个linux的qqnt 都要安图形界面
